### ISSUE TITLE
Add field in status to show the actual state of the back-end image

### ISSUE THREAD

**Issue by iamniting** [kube-storage/volume-replication-operator#44]
As of now, we have one field (State) in the status of volume replication CR which shows the state as replicating/Failed/Resyncing. But it does not tell us the actual state of the VR. We need one more field which tells us about the actual state of the Image at the backend. Adding one more field will give the user more clarity about the actual state in those scenarios when the user has edited the CR.

For example:
1. User has created a CR as Image State `Primary`. We will mark the State as `replicating` until reconcile failed.
2. User has edited the CR to change the image state as `Secondary` and reconcile failed we are going to mark the state as `Failed`. In this case, it is difficult for the user to know the state when he edits the CR many times.

**Comment by Madhu-1** [comment]
cc @ShyamsundarR @leseb

**Comment by leseb** [comment]
As example, this is what Rook reports at the pool levels it in the CephBlockPool CRD status field:

```yaml
status:
  info:
    rbdMirrorBootstrapPeerSecretName: pool-peer-token-replicapool
  mirroringInfo:
    lastChecked: "2021-03-12T15:16:10Z"
    mode: image
    site_name: 94824460-9eea-4d9c-b702-d7e2d30550e5-rook-ceph
  mirroringStatus:
    lastChecked: "2021-03-12T15:16:10Z"
    summary:
      daemon_health: UNKNOWN
      health: UNKNOWN
      image_health: OK
      states: {}
  phase: Ready
  snapshotScheduleStatus:
    lastChecked: "2021-03-12T15:16:10Z"
    snapshotSchedules:
    - image: '-'
      items:
      - interval: 12h
        start_time: 12:00:00-05:00
      - interval: 1d
        start_time: 14:00:00-05:00
      namespace: '-'
      pool: replicapool
```

So it makes sense to report `rbd mirror pool info/status` outputs.
